### ISSUE TITLE
not installed numpy on jetpack 4.4 on jetson nano2

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/jetson_nano#13]
Hi Dear,
I a few day spent for installation numpy on jetpack4.4, but I get this error, please guidance me:

```
sudo pip3 install numpy
WARNING: The directory '/home/jnano/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting numpy
  Downloading numpy-1.18.4.zip (5.4 MB)
     |████████████████████████████████| 5.4 MB 35 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpovsoyp_z
         cwd: /tmp/pip-install-sroqb4bl/numpy
    Complete output (158 lines):
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_mt19937.pyx
    Processing numpy/random/_philox.pyx
    Processing numpy/random/_generator.pyx
    Processing numpy/random/_bounded_integers.pyx.in
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/_sfc64.pyx
    Processing numpy/random/_pcg64.pyx
    Processing numpy/random/_common.pyx
    Processing numpy/random/_bit_generator.pyx
    Cythonizing sources
    blas_opt_info:
    blas_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      NOT AVAILABLE
    
    blis_info:
      libraries blis not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      NOT AVAILABLE
    
    openblas_info:
    C compiler: aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
    
    creating /tmp/tmpw7ja6mty/tmp
    creating /tmp/tmpw7ja6mty/tmp/tmpw7ja6mty
    compile options: '-c'
    aarch64-linux-gnu-gcc: /tmp/tmpw7ja6mty/source.c
    aarch64-linux-gnu-gcc -pthread /tmp/tmpw7ja6mty/tmp/tmpw7ja6mty/source.o -lopenblas -o /tmp/tmpw7ja6mty/a.out
      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/usr/lib/aarch64-linux-gnu']
        language = c
        define_macros = [('HAVE_CBLAS', None)]
    
      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/usr/lib/aarch64-linux-gnu']
        language = c
        define_macros = [('HAVE_CBLAS', None)]
    
    non-existing path in 'numpy/distutils': 'site.cfg'
    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      NOT AVAILABLE
    
    openblas_lapack_info:
    C compiler: aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC
    
    creating /tmp/tmpcl5ce_q6/tmp
    creating /tmp/tmpcl5ce_q6/tmp/tmpcl5ce_q6
    compile options: '-c'
    aarch64-linux-gnu-gcc: /tmp/tmpcl5ce_q6/source.c
    aarch64-linux-gnu-gcc -pthread /tmp/tmpcl5ce_q6/tmp/tmpcl5ce_q6/source.o -lopenblas -o /tmp/tmpcl5ce_q6/a.out
      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/usr/lib/aarch64-linux-gnu']
        language = c
        define_macros = [('HAVE_CBLAS', None)]
    
      FOUND:
        libraries = ['openblas', 'openblas']
        library_dirs = ['/usr/lib/aarch64-linux-gnu']
        language = c
        define_macros = [('HAVE_CBLAS', None)]
    
    running dist_info
    running build_src
    build_src
    building py_modules sources
    creating build
    creating build/src.linux-aarch64-3.6
    creating build/src.linux-aarch64-3.6/numpy
    creating build/src.linux-aarch64-3.6/numpy/distutils
    building library "npymath" sources
    creating build/src.linux-aarch64-3.6/numpy/core
    creating build/src.linux-aarch64-3.6/numpy/core/src
    creating build/src.linux-aarch64-3.6/numpy/core/src/npymath
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npymath/npy_math_internal.h
      adding 'build/src.linux-aarch64-3.6/numpy/core/src/npymath' to include_dirs.
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npymath/ieee754.c
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npymath/npy_math_complex.c
    None - nothing done with h_files = ['build/src.linux-aarch64-3.6/numpy/core/src/npymath/npy_math_internal.h']
    building library "npysort" sources
    creating build/src.linux-aarch64-3.6/numpy/core/src/common
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/npy_sort.h
      adding 'build/src.linux-aarch64-3.6/numpy/core/src/common' to include_dirs.
    creating build/src.linux-aarch64-3.6/numpy/core/src/npysort
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/quicksort.c
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/mergesort.c
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/timsort.c
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/heapsort.c
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/radixsort.c
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/npy_partition.h
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/selection.c
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/common/npy_binsearch.h
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/npysort/binsearch.c
    None - nothing done with h_files = ['build/src.linux-aarch64-3.6/numpy/core/src/common/npy_sort.h', 'build/src.linux-aarch64-3.6/numpy/core/src/common/npy_partition.h', 'build/src.linux-aarch64-3.6/numpy/core/src/common/npy_binsearch.h']
    building extension "numpy.core._multiarray_tests" sources
    creating build/src.linux-aarch64-3.6/numpy/core/src/multiarray
    conv_template:> build/src.linux-aarch64-3.6/numpy/core/src/multiarray/_multiarray_tests.c
    building extension "numpy.core._multiarray_umath" sources
    Running from numpy source directory.
    setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    /usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 158, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 250, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 143, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 488, in <module>
        setup_package()
      File "setup.py", line 480, in setup_package
        setup(**metadata)
      File "/tmp/pip-install-sroqb4bl/numpy/numpy/distutils/core.py", line 171, in setup
        return old_setup(**new_attr)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/dist_info.py", line 31, in run
        egg_info.run()
      File "/tmp/pip-install-sroqb4bl/numpy/numpy/distutils/command/egg_info.py", line 26, in run
        self.run_command("build_src")
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-sroqb4bl/numpy/numpy/distutils/command/build_src.py", line 146, in run
        self.build_sources()
      File "/tmp/pip-install-sroqb4bl/numpy/numpy/distutils/command/build_src.py", line 163, in build_sources
        self.build_extension_sources(ext)
      File "/tmp/pip-install-sroqb4bl/numpy/numpy/distutils/command/build_src.py", line 320, in build_extension_sources
        sources = self.generate_sources(sources, ext)
      File "/tmp/pip-install-sroqb4bl/numpy/numpy/distutils/command/build_src.py", line 380, in generate_sources
        source = func(extension, build_dir)
      File "numpy/core/setup.py", line 430, in generate_config_h
        moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)
      File "numpy/core/setup.py", line 49, in check_types
        out = check_types(*a, **kw)
      File "numpy/core/setup.py", line 288, in check_types
        "install {0}-dev|{0}-devel.".format(python))
    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpovsoyp_z Check the logs for full command output.
```

**Comment by jkjung-avt** [comment]
> SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.

Looks like you need to apt install 'python3-dev' first.

```
$ sudo apt-get install -y python3-dev python3-testresources python3-pip
$ sudo pip3 install -U pip
```

You could refer to my blog post, [JetPack-4.4 for Jetson Nano](https://jkjung-avt.github.io/jetpack-4.4/), for the exact steps of how I installed things on JetPack-4.4.

**Comment by Tetsujinfr** [comment]
@PythonImageDeveloper can you consider closing this issue if @jkjung-avt proposal solved your issue? thanks
