### ISSUE TITLE
請問您是否有調整過camera獲取的圖像的亮度

### ISSUE THREAD

**Issue by Stephenfang51** [jkjung-avt/jetson_nano#3]
首先非常感謝您的shell

如題

我的camera是CSI的， 也就是直接排線插在板子上

```
import cv2

def gstreamer_pipeline(
capture_width=1280,
capture_height=720,
display_width=1280,
display_height=720,
framerate=60,
flip_method=0,
):
return (
"nvarguscamerasrc ! "
"video/x-raw(memory:NVMM), "
"width=(int)%d, height=(int)%d, "
"format=(string)NV12, framerate=(fraction)%d/1 ! "
"nvvidconv flip-method=%d ! "
"video/x-raw, width=(int)%d, height=(int)%d, format=(string)BGRx ! "
"videoconvert ! "
"video/x-raw, format=(string)BGR ! appsink"
% (
capture_width,
capture_height,
framerate,
flip_method,
display_width,
display_height,
)
)

cap = cv2.VideoCapture(gstreamer_pipeline(flip_method=0), cv2.CAP_GSTREAMER)
brightness=0.8
cap.set(cv2.CAP_PROP_BRIGHTNESS,brightness)
while(True):
ret, frame = cap.read()
rgb = frame
cv2.imshow('frame', rgb)
key = cv2.waitKey(1)
if key == ord('x'):
break

cap.release
```

不過確報了以下錯誤
```
Traceback (most recent call last):
File "brightness.py", line 74, in <module>
show_camera()
File "brightness.py", line 61, in show_camera
cv2.imshow("CSI Camera", img)
cv2.error: /home/nvidia/build_opencv/opencv/modules/highgui/src/window.cpp:331: error: (-215) size.width>0 && size.height>0 in function imshow
```

明顯拿掉cap.set(cv2.CAP_PROP_BRIGHTNESS,brightness) 這個語句就不會報錯， 攝像頭正常開啟
不曉得您有沒有試過改變獲取的圖像亮度過的經驗可以分享呢 ？

十分感謝你 ！

**Comment by jkjung-avt** [comment]
1. 我想，"cap.set(cv2.CAP_PROP_BRIGHTNESS,brightness)"應該透過V4L2 API去下command，在使用gstreamer pipeline的狀況下，cv2.VideoCapture object應該不支援這個function call。你可查一下 "nvarguscamerasrc" 的文件看看該element是否能直接設置camera的brightness。

2. 修改image brightness是簡單的transformation，透過cv2可輕易做到，若要求降低CPU loading的話，也可考慮採用GPU去實作。

**Comment by Stephenfang51** [comment]
@jkjung-avt 

謝謝您的超快速回應

1.第一種 搜了一下似乎沒有修改的設置

看來只能用第二種方法來實現功能了， 但是GPU的實作是什麼概念呢？ 用CUDA嗎？
目前有嘗試過CPU上的transformation， 

但是好奇您說的在GPU是如何操作 謝謝

**Comment by jkjung-avt** [comment]
是，使用OpenCV裡的CUDA function，或是自己寫CUDA function來修改pixels的brightness值。

**Comment by Stephenfang51** [comment]
@jk
謝謝您的回復 ！再次感謝

**Comment by jk** [comment]
@Stephenfang51 genau so
